/**
 * generate-obj.js — Generate OBJ 3D mesh from elevation grid
 * Uses Delaunay triangulation via delaunator
 */

import Delaunator from 'delaunator';

/**
 * Generate OBJ file content from elevation grid data
 * @param {Object} gridData - Output of fetchElevationGrid
 * @param {Object} parcelGeometry - GeoJSON geometry for parcel boundary (optional)
 * @returns {Object} { obj: string, mtl: string }
 */
export function generateOBJ(gridData, parcelGeometry = null) {
  const { grid, nRows, nCols, lats, lngs, mPerDegLat, mPerDegLng, bbox } = gridData;
  const originLat = (bbox.minLat + bbox.maxLat) / 2;
  const originLng = (bbox.minLng + bbox.maxLng) / 2;

  // Collect valid vertices
  const vertices = [];
  const coords2D = []; // For Delaunay (flat array [x0,y0,x1,y1,...])

  for (let r = 0; r < nRows; r++) {
    for (let c = 0; c < nCols; c++) {
      const z = grid[r][c];
      if (z == null) continue;

      const lat = lats[r];
      const lng = lngs[c];
      const x = (lng - originLng) * mPerDegLng;
      const y = (lat - originLat) * mPerDegLat;

      vertices.push({ x, y, z });
      coords2D.push(x, y);
    }
  }

  if (vertices.length < 3) {
    throw new Error('Not enough valid elevation points for mesh generation');
  }

  console.log(`[obj] ${vertices.length} vertices, computing Delaunay triangulation...`);

  // Delaunay triangulation
  const delaunay = new Delaunator(coords2D);
  const triangles = delaunay.triangles;
  const numTriangles = triangles.length / 3;

  console.log(`[obj] ${numTriangles} triangles generated`);

  // Build OBJ content
  // OBJ convention: X=East, Y=Up(altitude), Z=South(negative North)
  let obj = '# Topo3D Antilles - Terrain mesh\n';
  obj += '# Generated by topo3d-antilles.com\n';
  obj += `# Vertices: ${vertices.length}, Faces: ${numTriangles}\n`;
  obj += 'mtllib terrain.mtl\n';
  obj += 'usemtl terrain_mat\n\n';

  // Vertices (swap Y/Z for OBJ Y-up convention)
  for (const v of vertices) {
    obj += `v ${v.x.toFixed(3)} ${v.z.toFixed(3)} ${(-v.y).toFixed(3)}\n`;
  }

  obj += '\n';

  // Faces (1-indexed)
  for (let i = 0; i < triangles.length; i += 3) {
    const a = triangles[i] + 1;
    const b = triangles[i + 1] + 1;
    const c = triangles[i + 2] + 1;
    obj += `f ${a} ${b} ${c}\n`;
  }

  // Material file
  const mtl = `# Topo3D Antilles - Terrain material
newmtl terrain_mat
Ka 0.3 0.25 0.2
Kd 0.6 0.55 0.4
Ks 0.1 0.1 0.1
Ns 10.0
d 1.0
illum 2
`;

  return { obj, mtl };
}
